version = 1

# Common excludes for Node.js projects
exclude_patterns = [
  "**/node_modules/**",
  "**/dist/**",
  "**/build/**",
  "**/coverage/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  # Указываем Node.js окружение для TypeScript проекта
  environment = ["nodejs"]

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true


