version: '3.8'

services:
  infisical-docker-sync:
    image: ghcr.io/webzaytsev/infisical-docker-sync:latest
    container_name: infisical-docker-sync
    volumes:
      - ./config.yaml:/app/data/config.yaml
      - ./envs:/app/envs
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
    environment:
      - TZ=Europe/Moscow
      - CONFIG_PATH=/app/data/config.yaml

  test-server:
    image: nginx:alpine
    container_name: test_container
    ports:
      - "8080:80"
