name: Build and Push Docker Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit SHA or tag to build from'
        required: false
        default: ''
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit || github.ref }}
          fetch-depth: 0  # Нужно для получения всех тегов

      - name: Get version from git
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            # При ручном запуске пытаемся найти тег для текущего коммита
            VERSION=$(git describe --tags --exact-match 2>/dev/null || echo "")
            if [ -n "$VERSION" ]; then
              echo "version=${VERSION#v}" >> $GITHUB_OUTPUT
              echo "is_release=true" >> $GITHUB_OUTPUT
            else
              echo "version=dev-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
              echo "is_release=false" >> $GITHUB_OUTPUT
            fi
          else
            # При push тега используем ref
            echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
            echo "is_release=true" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},enable=${{ github.event_name == 'push' }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ github.event_name == 'push' }}
            type=semver,pattern={{major}},enable=${{ github.event_name == 'push' }}
            type=raw,value=${{ steps.version.outputs.version }}
          labels: |
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.vendor=WebZaytsev
            org.opencontainers.image.version=${{ steps.version.outputs.version }}
            org.opencontainers.image.created={{date 'YYYY-MM-DD HH:mm:ss'}}
            org.opencontainers.image.revision={{sha}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
